# project definitions
project: argo_docs_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/argo_docs/designers
topnav_title: Jekyll Documentation Theme
homepage_title: Jekyll doc theme for designers
site_title: Jekyll theme for designers
project_folder: argo_docs
company_name: Your company
footer_image_location: ../common_images/company_logo.png
github_editme_path: tomjohnson1492/documentation-theme-jekyll/edit/reviews
disqus_shortname: idrbwjekyll
# variables

sidebar_tagline: Designers
sidebar_version: Version 4.0
theme_file: theme-blue.css
pdf_file_name: argo_docs_designers_pdf.pdf

port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/argo_docs_writers*

# same for all
host: 127.0.0.1
feedback_email: tomjohnson1492@gmail.com

markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

