destination: ../doc_outputs/argo_docs/designers-pdf
url: "http://127.0.0.1:4010"
baseurl: "/argo_docs/designers-pdf"
port: 4010
output: pdf
print_title: Jekyll theme for documentation — designers
print_subtitle: version 4.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true